version: "3.7"

volumes:
    vdomarkas-database:

networks:
    vdomarkas-network:

services:
    db:
        image: mysql:5.7
        volumes:
            - vdomarkas-database:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 8889:3306
        networks:
            - vdomarkas-network

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 3001:80
        networks:
            - vdomarkas-network

    vdomarkascom:
        depends_on:
            - db
        image: wordpress:latest
        restart: always
        ports:
            - 8080:80
            - 443:443
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        volumes:
            - ./vdomarkas:/var/www/html
        container_name: vdomarkas-site
        networks:
            - vdomarkas-network
