version: "2"

services:
    db:
        image: mariadb:latest
        container_name: db_server
        ports:
            - "3306:3306"
        volumes:
            - ./database/data:/var/lib/mysql
            - ./database/initdb.d:/docker-entrypoint-initdb.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # any random string will do
            MYSQL_DATABASE: ${MYSQL_DATABASE} # the name of your mysql database
            MYSQL_USER: ${MYSQL_USER} # the name of the database user
            MYSQL_PASSWORD: ${MYSQL_PASSWORD} # the password of the mysql user

    vdomarkascom:
        depends_on:
            - db
        image: wordpress:latest
        container_name: wp-web
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
        ports:
            - "${PORT:-8000}:80"
        restart: always
        volumes: ["./html:/var/www/html"]

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            MYSQL_USERNAME: ${MYSQL_USER}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always
        ports:
            - 8080:80
        links:
            - db
