name: DO_DEPLOY

on:
    push:
        branches: [main]

jobs:
    Build:
        runs-on: self-hosted

        steps:
            - run: sudo chown -R vik:vik /home/actions-runner/_work/wp-docker-ci-cd
            - uses: actions/checkout@main
            - name: Create .env
              run: |
                  echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
                        MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
                        MYSQL_USER=${{ secrets.MYSQL_USER }}
                        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" > .env
            - name: Run build
              run: docker-compose up -d
