name: DO_DEPLOY

on:
    push:
        branches: [main]

jobs:
    Build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@main
            - name: Create .env
              run: echo 'PORT=${{ secrets.PORT }} MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} MYSQL_USER=${{ secrets.MYSQL_USER }} MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }}' > .env
            - name: Run build
              run: docker-compose up -d
