name: DO_DEPLOY

on:
    push:
        branches: [main]

jobs:
    configure:
        runs-on: ubuntu-latest
        outputs:
            uid_gid: ${{ steps.get-user.outputs.uid_gid }}
        steps:
            - id: get-user
              run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

        clone-and-install:
          needs: configure
          runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
            options: --user ${{ needs.configure.outputs.uid_gid }}
        steps:
            - uses: actions/checkout@v2
    Build:
        runs-on: self-hosted

        steps:
            - run: sudo chown -R vik:vik /home/actions-runner/_work/wp-docker-ci-cd
            - uses: actions/checkout@main
            - name: Create .env
              run: |
                  echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
                        MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
                        MYSQL_USER=${{ secrets.MYSQL_USER }}
                        MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" > .env
            - name: Run build
              run: docker-compose up -d
