name: DO_DEPLOY

on:
    push:
        branches: [main]

jobs:
    Build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@main
            - name: Create .env
              run: |
              echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
              
              echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" > .env

              echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" > .env
              
              echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" > .env
            - name: Run build
              run: docker-compose up -d
